OnlineShop/Pages/Customers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineShop.DataAccess;
using OnlineShop.DTO;

namespace OnlineShop.Pages
{
    public class CustomersModel : PageModel
    {
        public readonly IDataAccess<CustomerDTO> _custAccess;
        public readonly IDataAccess<CardDTO> _cardAccess;
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public List<CustomerDTO> Customers { get; set; }
        [BindProperty]
        public CustomerDTO Customer { get; set; }
        [BindProperty]
        public List<CardDTO> Card { get; set; }
        [BindProperty]
        public int CustomerId { get; set; }

        public CustomersModel(IDataAccess<CustomerDTO> dataAccess, IDataAccess<CardDTO> cardAccess)
        {
            _custAccess = dataAccess;
            _cardAccess = cardAccess;
            
        }
        public void OnGet()
        {
            Customers = _custAccess.ShowAll().ToList();
            Customer = _custAccess.GetById(CustomerId);
        }
        public IActionResult OnPostCustomer()
        {
            Customer = _custAccess.GetById(Customer.CustomerId);
            HttpContext.Session.SetInt32("CustomerId", Customer.CustomerId);
            if (ModelState.IsValid)
            {
                return RedirectToPage("/Products");
            }
            return Page();
        }


    }
}

OnlineShop/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OnlineShop/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OnlineShop/Pages/Orders.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineShop.DataAccess;
using OnlineShop.DTO;

namespace OnlineShop.Pages
{
    public class OrdersModel : PageModel
    {
        public readonly IDataAccess<OrderDTO> orderAccess;
        public readonly IDataAccess<ShoppingCartDTO> cartAccess;
        public readonly IDataAccess<CustomerDTO> custAccess;
        public readonly IDataAccess<CardDTO> cardAccess;
        public readonly IDataAccess<ProductDTO> prodAccess;
        private readonly IDataAccess<RecieptDTO> receiptAccess;

        [BindProperty]
        public int Id { get; set; }
        public List<OrderDTO> Orders { get; set; }
        public CustomerDTO Customer { get; set; }


        public OrdersModel(IDataAccess<OrderDTO> orderAccess, IDataAccess<ShoppingCartDTO> cartAccess, IDataAccess<CustomerDTO> custAccess, IDataAccess<CardDTO> cardAccess, IDataAccess<ProductDTO> prodAccess, IDataAccess<RecieptDTO> receiptAccess)
        {
            this.orderAccess = orderAccess;
            this.cartAccess = cartAccess;
            this.custAccess = custAccess;
            this.cardAccess = cardAccess;
            this.prodAccess = prodAccess;
            this.receiptAccess = receiptAccess;
        }
        public IActionResult OnGetPlaceOrder()
        {
            int? Id = HttpContext.Session.GetInt32("CustomerId");
            ShoppingCartDTO userCart = cartAccess.GetById(Id.Value);
            if (userCart == null)
            {
                return RedirectToPage("/Customers");
            }
            else
            {
                CustomerDTO Customer = custAccess.GetById(Id.Value);
                OrderDTO newOrder = new OrderDTO(0, Customer, userCart.Products);
                orderAccess.Save(newOrder);
                cartAccess.Update(new ShoppingCartDTO(Id.Value));
                return RedirectToPage("/Orders");
            }
        }

       
        public IActionResult OnGet()
        {
            int? Id = HttpContext.Session.GetInt32("CustomerId");
            if (Id.HasValue)
            {
                Orders = orderAccess.ShowAll().Where(o => o.Customer.CustomerId == Id.Value).ToList();
                return Page();
            }
            else
            {
                return RedirectToPage("/Customers");
            }


        }
        public IActionResult OnPostPay()
        {
            Orders = orderAccess.ShowAll().ToList();
            var order = orderAccess.GetById(Id);
            if (!order.IsPaid)
            {
                order.IsPaid = true;
                orderAccess.Update(order);
                receiptAccess.Save(new RecieptDTO() { Order = order });
            }

            return RedirectToPage("/Receipts");
        }
        public IActionResult OnPostReceipt()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/Receipts");
            }
            else
            {
                return Page();
            }
        }
    }
}

OnlineShop/Pages/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineShop.DataAccess;
using OnlineShop.DTO;

namespace OnlineShop.Pages.Shared
{
    public class ProductsModel : PageModel
    {
        public readonly IDataAccess<ProductDTO> _dataAccess;
        public readonly IDataAccess<CustomerDTO> _custAccess;

        [BindProperty]
        public List<ProductDTO> Products { get; set; }
        [BindProperty]
        public ProductDTO Product { get; set; }
        public int ProductID { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }
        public ProductsModel(IDataAccess<ProductDTO> dataAccess, IDataAccess<CustomerDTO> custAccess)
        {
            _dataAccess = dataAccess;
            _custAccess = custAccess;
        }
        public IActionResult OnGet()
        {
            int? id = HttpContext.Session.GetInt32("CustomerId");
            if (id.HasValue)
            {
                Products = _dataAccess.ShowAll().ToList();
                return Page();
            }
            else
            {
                return RedirectToPage("/Customers");
            }
        }
        public ActionResult OnPostSearch()
        {
            if (!string.IsNullOrEmpty(SearchTerm))
            {
                Products = _dataAccess.ShowAll().Where(p => p.ProductName.ToLower().Contains(SearchTerm.ToLower())).ToList();
                return Page();
            }
            return RedirectToPage("/Products");
        }
        public IActionResult OnPostAddToCart()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage("/Shoppingcart");
            }
            return Page();
        }

        public IActionResult OnPostSortPriceUp()
        {
            Products = _dataAccess.ShowAll().ToList().OrderBy(p => p.Price).ToList();
            return Page();
        }
        public IActionResult OnPostSortPriceDown()
        {
            Products = _dataAccess.ShowAll().ToList().OrderByDescending(p => p.Price).ToList();
            return Page();
        }
    }
}

OnlineShop/Pages/Receipts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineShop.DataAccess;
using OnlineShop.DTO;

namespace OnlineShop.Pages
{
    public class ReceiptsModel : PageModel
    {
        private readonly IDataAccess<RecieptDTO> receiptAccess;
        public readonly IDataAccess<CustomerDTO> custAccess;
        public readonly IDataAccess<CardDTO> cardAccess;
        public readonly IDataAccess<OrderDTO> orderAccess;


        public List<RecieptDTO> Receipts { get; set; }
        public ReceiptsModel(IDataAccess<RecieptDTO> receiptAccess, IDataAccess<CustomerDTO> custAccess, IDataAccess<CardDTO> cardAccess)
        {
            this.receiptAccess = receiptAccess;
            this.custAccess = custAccess;
            this.cardAccess = cardAccess;
        }
        public void OnGet()
        {
            int? Id = HttpContext.Session.GetInt32("CustomerId");
            Receipts = receiptAccess.ShowAll().ToList().Where(x => x.Order.Customer.CustomerId == Id).ToList();
        }

    }
}

OnlineShop/Pages/Shoppingcart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineShop.DataAccess;
using OnlineShop.DTO;

namespace OnlineShop.Pages
{
    public class ShoppingcartModel : PageModel
    {
        public readonly IDataAccess<ProductDTO> prodAccess;
        public readonly IDataAccess<CustomerDTO> custAccess;
        private readonly IDataAccess<ShoppingCartDTO> cartAccess;



        public CustomerDTO Customer { get; set; }
        public List<ProductDTO> ShoppingCart { get; set; }



        public ShoppingcartModel(IDataAccess<ProductDTO> prodAccess, IDataAccess<CustomerDTO> custAccess, IDataAccess<ShoppingCartDTO> cartAccess)
        {
            this.prodAccess = prodAccess;
            this.custAccess = custAccess;
            this.cartAccess = cartAccess;
        }
        public IActionResult OnGet()
        {
            int? id = HttpContext.Session.GetInt32("CustomerId");
            if (id.HasValue)
            {
                ShoppingCartDTO userCart = cartAccess.GetById(id.Value);
                if (userCart == null)
                {
                    userCart = new(id.Value);
                    cartAccess.Save(userCart);
                    ShoppingCart = userCart.Products;
                    return Page();
                }
                else
                {
                    ShoppingCart = userCart.Products;
                    return Page();
                }
            }
            else
            {
                return RedirectToPage("/Customers");
            }
        }
        public IActionResult OnPostRemove(int index)
        {
            int? Id = HttpContext.Session.GetInt32("CustomerId");
            ShoppingCartDTO userCart = cartAccess.GetById(Id.Value);
            userCart.Products.RemoveAt(index);
            cartAccess.Update(userCart);
            return RedirectToPage("/Shoppingcart");

        }

        public IActionResult OnPostAddToCart(int ProductId)
        {

            int? Id = HttpContext.Session.GetInt32("CustomerId");
            ShoppingCartDTO userCart = cartAccess.GetById(Id.Value);
            if (userCart == null)
            {
                userCart = new(Id.Value);
                ProductDTO product = prodAccess.GetById(ProductId);
                userCart.Products.Add(product);
                cartAccess.Save(userCart);
            }
            else
            {
                ProductDTO product = prodAccess.GetById(ProductId);
                userCart.Products.Add(product);
                cartAccess.Update(userCart);
            }
            return RedirectToPage("/Products");
        }

    }
}

OnlineShop/Pages/Customers.cshtml
@page
@model OnlineShop.Pages.CustomersModel
@{
}

<h1>Please Choose a customer for shopping</h1>
<div>

    @foreach (var customer in Model.Customers.ToList())
    {

        <div class="card-body">
            <h5 class="card-title">@customer.Name</h5>
            <p class="card-text">@customer.Email</p>
           
                
                
                    <p class="card-text">Cardnumber: @customer.Card</p>
                    <form asp-page-handler="Customer">
                        <input asp-for="@customer.CustomerId" type="hidden" value="@customer.CustomerId" />

                        <button type="submit" class="btn btn-primary">Use for shopping</button>
                    </form>


                
         

        </div>
    }

</div>

OnlineShop/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OnlineShop/Pages/Orders.cshtml
@page
@model OnlineShop.Pages.OrdersModel
@using Microsoft.AspNetCore.Http;
<p>Using: @Model.custAccess.GetById((int)HttpContext.Session.GetInt32("CustomerId")).Name</p>


<h1>Orders</h1>
@foreach (var cart in Model.Orders)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">
                    Product
                </th>
                <th scope="col">
                    Price
                </th>
                <th scope="col">
                    Paid
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in cart.Products)
            {
                <tr>
                    <td>
                        @product.ProductName
                    </td>
                    <td>
                        @product.Price.ToString("C")
                    </td>
                    <td>
                        @cart.IsPaid
                    </td>

                </tr>
            }


        </tbody>

    </table>
    <form method="post">
        <input type="hidden" asp-for="Id" value="@cart.OrderID" />
        @if (!cart.IsPaid)
        {
            <button class="btn btn-outline-primary" asp-page-handler="Pay">Pay</button>
        }
        else
        {
            <button class="btn btn-outline-primary" asp-page-handler="Pay">Receipt</button>
        }
    </form>
}
<p>Payment Option: CardNumber: @Model.custAccess.GetById((int)HttpContext.Session.GetInt32("CustomerId")).Card</p>

OnlineShop/Pages/Products.cshtml
@page
@model OnlineShop.Pages.Shared.ProductsModel
@using Microsoft.AspNetCore.Http;
@{
}
<h2>Welcome to my online shop</h2>
<p> @Model._custAccess.GetById((int)HttpContext.Session.GetInt32("CustomerId")).Name Which mobile would you like to buy?</p> 
<div class="container-fluid">
    <form asp-page-handler="Search">
        <div class="d-flex">
            <div class="input-group">
                <input class="form-control" asp-for="SearchTerm" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </div>
    </form>
   
        <div class="dropdown">
            <button class="btn dropdown-toggle" asp-page="/Order" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sort
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <form asp-page-handler="SortPriceUp" method="post">
                    <button type="submit" class="btn btn-primary">By Lowest</button>
                </form>
                <form asp-page-handler="SortPriceDown" method="post">
                    <button type="submit" class="btn btn-primary">By Highest</button>
                </form>
            </div>
        </div>
    
    
    @foreach (var product in Model.Products.ToList())
    {

        <img class="card-img-top w-50" src="/Pictures/@product.ImagePath" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@product.ProductName</h5>
            <p class="card-text">@product.ProductDescription</p>
            <p class="card-text">Current Price: @product.Price:-</p>
            <form asp-page-handler="AddToCart" asp-page="/Shoppingcart" method="post">
                <input type="hidden" name="ProductId" value="@(product.ProductId)" />
                <button class="btn btn-primary" type="submit">Add to cart</button>
            </form>

        </div>
    }
</div>

OnlineShop/Pages/Receipts.cshtml
@page
@model OnlineShop.Pages.ReceiptsModel
@{
    ViewData["Title"] = "Receipts";
}
@using Microsoft.AspNetCore.Http;

<h1>Receipt</h1>

@{double sum = 0;}
@foreach (var receipt in Model.Receipts)
{
    <h4>Receipt number: @receipt.RecieptNumber</h4>
    <p>Name: @Model.custAccess.GetById((int)HttpContext.Session.GetInt32("CustomerId")).Name</p>
    <p>Paid with: @Model.custAccess.GetById((int)HttpContext.Session.GetInt32("CustomerId")).Card</p>
    <p>Paid at: @DateTime.Now </p>
    @foreach (var product in receipt.Order.Products)
    {
        sum += product.Price;
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <p>@product.ProductName</p>
                <p>@product.Price.ToString("C")</p>

            </li>
        </ul>

        <br />
    }
    <h4>Total Sum: @sum.ToString("C")</h4>
    { sum = 0; }
    <br />

}

OnlineShop/Pages/Shoppingcart.cshtml
@page
@model OnlineShop.Pages.ShoppingcartModel
@using Microsoft.AspNetCore.Http;
<p>Using: @Model.custAccess.GetById((int)HttpContext.Session.GetInt32("CustomerId")).Name</p>
<h1>Shopping Cart</h1>
<div class="container-fluid">
    @{double sum = 0;}
    @for (int i = 0; i < Model.ShoppingCart.Count; i++)
    {
        var product = Model.ShoppingCart[i];
        sum += product.Price;

    <div>
        <img class="card-img-top w-25" src="/Pictures/@product.ImagePath" alt="Card image cap">
        <br />
        Product: @product.ProductName; <br />
        Price: @product.Price.ToString("N");
        <span>
            <br />
            <form asp-page="/Shoppingcart" asp-page-handler="Remove" method="post">
                <input type="hidden" name="index" value="@i" />
                <button type="submit" class="btn btn-outline-danger">Remove</button>
            </form>
        </span>
    </div>

     }
</div>
<div>Total Sum :@sum.ToString("N")</div>
<div>
    <a asp-page="/Orders" asp-page-handler="PlaceOrder" class="btn btn-success">Place Order</a>
</div>